# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Flutter SDK (stable) in einem Container nutzen
  - name: "ghcr.io/cirruslabs/flutter:stable"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        echo "Repo Inhalt:"
        ls -la

        echo "Wechsle in frontend/"
        cd frontend
        ls -la

        flutter --version
        flutter pub get
        flutter analyze

        # Tests nur, wenn vorhanden
        flutter test || true

        # Web build (falls ihr Web braucht)
        flutter build web --release
