# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "node:20"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        npm ci
        npm test --if-present
        npm run build --if-present
