// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/temperature.proto

package temperature

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CelsiusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Celsius       float64                `protobuf:"fixed64,1,opt,name=celsius,proto3" json:"celsius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CelsiusRequest) Reset() {
	*x = CelsiusRequest{}
	mi := &file_proto_temperature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CelsiusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CelsiusRequest) ProtoMessage() {}

func (x *CelsiusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_temperature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CelsiusRequest.ProtoReflect.Descriptor instead.
func (*CelsiusRequest) Descriptor() ([]byte, []int) {
	return file_proto_temperature_proto_rawDescGZIP(), []int{0}
}

func (x *CelsiusRequest) GetCelsius() float64 {
	if x != nil {
		return x.Celsius
	}
	return 0
}

type KelvinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kelvin        float64                `protobuf:"fixed64,1,opt,name=kelvin,proto3" json:"kelvin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KelvinResponse) Reset() {
	*x = KelvinResponse{}
	mi := &file_proto_temperature_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KelvinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KelvinResponse) ProtoMessage() {}

func (x *KelvinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_temperature_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KelvinResponse.ProtoReflect.Descriptor instead.
func (*KelvinResponse) Descriptor() ([]byte, []int) {
	return file_proto_temperature_proto_rawDescGZIP(), []int{1}
}

func (x *KelvinResponse) GetKelvin() float64 {
	if x != nil {
		return x.Kelvin
	}
	return 0
}

var File_proto_temperature_proto protoreflect.FileDescriptor

const file_proto_temperature_proto_rawDesc = "" +
	"\n" +
	"\x17proto/temperature.proto\x12\vtemperature\"*\n" +
	"\x0eCelsiusRequest\x12\x18\n" +
	"\acelsius\x18\x01 \x01(\x01R\acelsius\"(\n" +
	"\x0eKelvinResponse\x12\x16\n" +
	"\x06kelvin\x18\x01 \x01(\x01R\x06kelvin2a\n" +
	"\x12TemperatureService\x12K\n" +
	"\x0fCelsiusToKelvin\x12\x1b.temperature.CelsiusRequest\x1a\x1b.temperature.KelvinResponseB!Z\x1fgrpc-celsius-kelvin/temperatureb\x06proto3"

var (
	file_proto_temperature_proto_rawDescOnce sync.Once
	file_proto_temperature_proto_rawDescData []byte
)

func file_proto_temperature_proto_rawDescGZIP() []byte {
	file_proto_temperature_proto_rawDescOnce.Do(func() {
		file_proto_temperature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_temperature_proto_rawDesc), len(file_proto_temperature_proto_rawDesc)))
	})
	return file_proto_temperature_proto_rawDescData
}

var file_proto_temperature_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_temperature_proto_goTypes = []any{
	(*CelsiusRequest)(nil), // 0: temperature.CelsiusRequest
	(*KelvinResponse)(nil), // 1: temperature.KelvinResponse
}
var file_proto_temperature_proto_depIdxs = []int32{
	0, // 0: temperature.TemperatureService.CelsiusToKelvin:input_type -> temperature.CelsiusRequest
	1, // 1: temperature.TemperatureService.CelsiusToKelvin:output_type -> temperature.KelvinResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_temperature_proto_init() }
func file_proto_temperature_proto_init() {
	if File_proto_temperature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_temperature_proto_rawDesc), len(file_proto_temperature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_temperature_proto_goTypes,
		DependencyIndexes: file_proto_temperature_proto_depIdxs,
		MessageInfos:      file_proto_temperature_proto_msgTypes,
	}.Build()
	File_proto_temperature_proto = out.File
	file_proto_temperature_proto_goTypes = nil
	file_proto_temperature_proto_depIdxs = nil
}
